name = "plads-web"
main = "src/index.js"
compatibility_date = "2025-11-17"

[assets]
directory = "."
binding = "ASSETS"

[env.production]
name = "plads-web"
vars = { ENVIRONMENT = "production" }

[[env.production.routes]]
pattern = "plads.cl/*"
zone_name = "plads.cl"
